### PR TITLE
Check if document exists before trying to access it

### LINKED ISSUE #79: ReferenceError: document is not defined in SSR context
**Describe the bug**
The injected code on line 3 `if ('adoptedStyleSheets' in document) { return; }` fails in a node environment because document not defined

**To Reproduce**
Run this code in an SSR context

**Expected behavior**
Expected to catch this case and return early.

### PR DESCRIPTION
**Pull request by hennessyevan**
Fixes #79

### CODE REVIEW

**Review by Lodin — APPROVED** [review]
LGTM

**Comment by hennessyevan** [comment]
Would it be possible to include this in 3.0? Or be merged into 2.x soon?

**Comment by calebdwilliams** [comment]
This was released to `construct-style-sheets-polyfill@2.4.17` which will likely be the final release on 2.0. I'll also add this in to 3.0 before merging to master.

**Comment by calebdwilliams** [comment]
This was also added to the full release of 3.0.

**Pull request merged**
