### PR TITLE
Fix for #54

### LINKED ISSUE #54: removeExcludedStyleSheets doesn't remove any stylesheets after it finds a non-excluded sheet
**Describe the bug**

Short version: [this line][1] should be `continue` not `return`.

[1]: https://github.com/calebdwilliams/construct-style-sheets/blob/b6b1988ec842ba60059436811a7ed4707771bd1d/src/adopt.js#L84

Slightly longer version: when checking for excluded stylesheets, `removeExcludedStyleSheets` returns after finding a stylesheet that should not be included. This prevents it from checking additional stylesheets.

**To Reproduce**

Given two stylesheets `s1` and `s2`:

```
document.adoptedStyleSheets = [ s1, s2 ]
document.adoptedStyleSheets = [ s1 ]
```

will fail to remove `s2` because it finds `s1` first.

**Expected behavior**

The stylesheet `s2` is removed.

### PR DESCRIPTION
**Pull request by dyoder**
Fixes #54

### CODE REVIEW

**Comment by calebdwilliams** [comment]
This looks right. Can we add a test to make sure this is working though?

**Comment by calebdwilliams** [comment]
Hey, would you mind rebasing this and using a standard commit? Something like `fix: remove styles properly` or something so this fix gets versioned correctly? Sorry to be a stickler about that. Once we have that, I can merge this but won’t be able to release until Friday.

**Comment by dyoder** [comment]
Sure. And no rush on the release.

**Comment by dyoder** [comment]
> Once we have that, I can merge this but won’t be able to release until …

Any updates on when this will be available? Thank you!

**Comment by calebdwilliams** [comment]
I started to but now have some tests failing on my computer. I’m guessing the implementation has been updated in Chrome. I started to test and then got distracted. 

Thanks for the reminder.

**Pull request closed without merging**
