### PR TITLE
Fix Safari broken rules

### PR DESCRIPTION
**Pull request by Lodin**
Adds a detection and correction for Safari broken rules mentioned in #84.

### CODE REVIEW

**Comment by Lodin** [comment]
@calebdwilliams, could you please test this solution? Since I'm a Windows user, testing on Mac is pretty inconvenient for me. I'm concerned about if it correctly detects Safari browser and how many cases are supported correctly.

**Comment by Lodin** [comment]
Hmm, maybe I have an idea of a better solution...

**Comment by calebdwilliams** [comment]
@Lodin keep me posted

**Comment by Lodin** [comment]
@calebdwilliams, I believe I finished the fix. Please test it with the Safari a bit more, because it might be that I haven't considered all the possible cases here.

**Comment by Lodin** [comment]
@calebdwilliams, do not mind my changes after the previous comment. That's mostly cosmetic optimizations. Please review and merge whenever you want.

**Review by calebdwilliams — APPROVED** [review]
The code here looks good to me, but the first time I tested this, Safari crashed. I don't think the two are related, but I'm going to try to stress test this a bit first before merging/releasing.

**Pull request merged**
