### PR TITLE
Add Github CI/CD

### PR DESCRIPTION
**Pull request by Lodin**
This PR introduces CI/CD based on Github actions. They are preferable to use because Github supports various platform including Windows and Mac OS that allows running tests in IE11 and Safari which increases a chance to catch an error in the code.

The results of test run can be found [here](https://github.com/Lodin/construct-style-sheets/actions).

This PR would also require enabling Github Action Beta for the repository.

### CODE REVIEW

**Comment by calebdwilliams** [comment]
I’m going to leave this open for now, but would like Actions to be fully released to merge. Just realized I hadn’t responded.

**Comment by Lodin** [comment]
Well, Github Actions are released, could you take a look at this PR now? I updated it according to fixed features that were absent when I created the initial PR.

Unfortunately, it also means that Codecov won't be able to work because of some [new restrictions](https://github.com/codecov/codecov-node#usage) they introduced. It requires some tokens to work with CI systems they do not recognize or something like that.

We would need to get these tokens or, probably, switch to another platform.

Personally, I decided to switch to [SonarCloud](https://sonarcloud.io) because it provides not only the code coverage visualization but also a static code analysis. It can combine the coverage results from different systems (e.g., windows and mac OS) into a single coverage as well. I can create a PR to implement it, but you would need to make some preparations like creating an account there if you don't have one and providing the SonarCloud secret key at the `Secret` page of repository settings.

I have it working already in some repositories: e.g., [custom-builtin-elements](https://github.com/corpusculejs/custom-builtin-elements) and [corpuscule](https://github.com/corpusculejs/corpuscule); you can see how it works, and take a look at the SonarCloud dashboard (you can find it by following SonarCloud badge links).

**Comment by calebdwilliams** [comment]
Yeah, I'll start to take a look at this one over the next week. I don't know nearly enough about GitHub Actions just yet to accept this, so I'd like to do some research.

**Comment by calebdwilliams** [comment]
Hey, I'm ready to bring this in. I know it's been awhile, but if we could resolve the conflicts here, I'd be happy to get this merged finally.

**Comment by Lodin** [comment]
Hi Caleb. Sorry for the long delay. Ok, I'll work on update (a lot of things changed since September 2019).

**Comment by calebdwilliams** [comment]
@Lodin, no worries. That’s why I wanted to hold off originally. Thanks for the effort.

**Comment by calebdwilliams** [comment]
Hey @Lodin are you still interested in setting this up? I’ve been wanting to migrate but would gladly take the PR or should we close this for now?

**Comment by Lodin** [comment]
Hi @calebdwilliams.

Yeah, sorry for such a delay. I still want to work on that; in the latest six month I was quite busy though. Gonna try to make something useful during February.

Sorry again, didn't expect that I'd be so busy for so long time.

**Comment by calebdwilliams** [comment]
No worries whatsoever. I appreciate all of your contributions and look forward to more!

**Comment by Lodin** [comment]
Hi @calebdwilliams! I think I finished this PR, and it is ready for review and merge. Sorry for delay.

I only wonder why doesn't it trigger an action already? When I added actions for my repos, the action started from the PR. Because of fork, probably?.. We need to figure out how to test actions then.

**Review by calebdwilliams — APPROVED** [review]
LGTM

**Pull request merged**
